name:SimplePipeline

on:
  push:
    branches: [main]

jobs:
  lintTest:
    name:Lint
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies 
        run: |
          echo "Running Installing Dependencies..."
      - name: Run Linting
        run: |
          echo "Running Linting tests..."
          npm run lint
        env:
          CI: true